from pathlib import Path

SCRIPT = Path('scripts/apply_barmm_parliamentary_election_bb.py')
TEST = Path('tests/test_barmm_parliamentary_election_bb.py')

text = SCRIPT.read_text(encoding='utf-8')
old_import = 'from world_signals.live_intelligence import validate_live_intelligence\nfrom world_signals.validation import validate_registry\n'
new_import = 'from world_signals.live_intelligence import validate_live_intelligence\nfrom world_signals.checkpoint_contract import version_at_least\nfrom world_signals.validation import validate_registry\n'
if old_import not in text:
    raise SystemExit('BB import anchor missing')
text = text.replace(old_import, new_import, 1)

anchor = 'def assert_target(plan: dict[str, Any], target: dict[str, Any]) -> None:\n'
helper = '''def assert_population_descendant_floors(\n    post: dict[str, Any],\n    live_schema: dict[str, Any],\n    live_observations: dict[str, Any],\n    live_evidence: dict[str, Any],\n    analysis_schema: dict[str, Any],\n    reviews: dict[str, Any],\n    analysis_evidence: dict[str, Any],\n) -> None:\n    \"\"\"Preserve BB's historical downstream checkpoint without freezing later reviewed growth.\"\"\"\n    require(version_at_least(live_schema.get(\"version\"), post[\"live_schema_version\"]), \"BB descendant Live schema fell below checkpoint\")\n    require(version_at_least(live_observations.get(\"version\"), post[\"live_schema_version\"]), \"BB descendant Live observations version fell below checkpoint\")\n    require(version_at_least(live_evidence.get(\"version\"), post[\"live_schema_version\"]), \"BB descendant Live evidence version fell below checkpoint\")\n    require(len(live_observations.get(\"observations\", [])) >= post[\"live_observation_count\"], \"BB descendant Live population fell below checkpoint\")\n    require(len(live_evidence.get(\"evidence\", [])) >= post[\"live_evidence_count\"], \"BB descendant Live evidence fell below checkpoint\")\n    require(version_at_least(analysis_schema.get(\"version\"), post[\"analysis_schema_version\"]), \"BB descendant Analysis schema fell below checkpoint\")\n    require(version_at_least(reviews.get(\"version\"), post[\"analysis_reviews_version\"]), \"BB descendant Analysis reviews version fell below checkpoint\")\n    require(version_at_least(analysis_evidence.get(\"version\"), post[\"analysis_reviews_version\"]), \"BB descendant Analysis evidence version fell below checkpoint\")\n    require(len(reviews.get(\"reviews\", [])) >= post[\"analysis_review_count\"], \"BB descendant Analysis reviews fell below checkpoint\")\n    require(len(analysis_evidence.get(\"evidence\", [])) >= post[\"analysis_evidence_count\"], \"BB descendant Analysis evidence fell below checkpoint\")\n    require(production_live_input_count(reviews) >= post[\"production_live_input_count\"], \"BB descendant production live-input count fell below checkpoint\")\n    require(production_analysis_revision_count(reviews) >= post[\"production_analysis_revision_count\"], \"BB descendant Analysis revision count fell below checkpoint\")\n    require(exact_series_count(reviews) >= post[\"production_exact_timestamp_series_count\"], \"BB descendant exact-series population fell below checkpoint\")\n\n\n'''
if anchor not in text:
    raise SystemExit('BB assert_target anchor missing')
text = text.replace(anchor, helper + anchor, 1)

old_block = '''    require(len(live_observations.get("observations", [])) == post["live_observation_count"], "BB target changed Live population")\n    require(len(live_evidence.get("evidence", [])) == post["live_evidence_count"], "BB target changed Live evidence")\n    require(len(reviews.get("reviews", [])) == post["analysis_review_count"], "BB target changed Analysis reviews")\n    require(len(analysis_evidence.get("evidence", [])) == post["analysis_evidence_count"], "BB target changed Analysis evidence")\n    require(production_live_input_count(reviews) == post["production_live_input_count"], "BB target changed production live-input count")\n    require(production_analysis_revision_count(reviews) == post["production_analysis_revision_count"], "BB target changed Analysis revisions")\n    require(exact_series_count(reviews) == post["production_exact_timestamp_series_count"], "BB target changed exact-series population")\n\n    require("Canonical Registry: **v0.39 / 689 occurrences**" in target["status"], "BB status target count missing")\n    require("BB repairs an upstream Southeast Asian election-coverage omission" in target["status"], "BB status target decision missing")\n    require("BB — BARMM election source + Canonical coverage repair" in target["roadmap"], "BB roadmap target missing")\n'''
new_block = '''    assert_population_descendant_floors(\n        post,\n        live_schema,\n        live_observations,\n        live_evidence,\n        analysis_schema,\n        reviews,\n        analysis_evidence,\n    )\n\n    # PROJECT_STATUS / ROADMAP are recovery and planning documentation, not BB-owned\n    # governed identities. Exact BB transform tests freeze what BB wrote historically;\n    # later reviewed overrides may summarise or supersede that prose.\n'''
if old_block not in text:
    raise SystemExit('BB exact population/documentation block missing')
text = text.replace(old_block, new_block, 1)
SCRIPT.write_text(text, encoding='utf-8')

text = TEST.read_text(encoding='utf-8')
text = text.replace('import json\n', 'import copy\nimport json\n', 1)
old_population_test = '''    def test_live_and_analysis_populations_are_not_touched(self) -> None:\n        post = self.plan["postconditions"]\n        live_observations = apply_bb.load(apply_bb.LIVE_OBSERVATIONS_PATH)\n        live_evidence = apply_bb.load(apply_bb.LIVE_EVIDENCE_PATH)\n        reviews = apply_bb.load(apply_bb.ANALYSIS_REVIEWS_PATH)\n        analysis_evidence = apply_bb.load(apply_bb.ANALYSIS_EVIDENCE_PATH)\n        self.assertEqual(len(live_observations["observations"]), post["live_observation_count"])\n        self.assertEqual(len(live_evidence["evidence"]), post["live_evidence_count"])\n        self.assertEqual(len(reviews["reviews"]), post["analysis_review_count"])\n        self.assertEqual(len(analysis_evidence["evidence"]), post["analysis_evidence_count"])\n        self.assertEqual(apply_bb.production_live_input_count(reviews), 1)\n        self.assertEqual(apply_bb.production_analysis_revision_count(reviews), 0)\n        self.assertEqual(apply_bb.exact_series_count(reviews), 0)\n'''
new_population_test = '''    def test_historical_downstream_checkpoint_is_exact_but_later_reviewed_growth_is_allowed(self) -> None:\n        post = self.plan["postconditions"]\n        self.assertEqual(post["live_schema_version"], "0.4")\n        self.assertEqual(post["live_observation_count"], 4)\n        self.assertEqual(post["live_evidence_count"], 6)\n        self.assertEqual(post["analysis_schema_version"], "0.7")\n        self.assertEqual(post["analysis_reviews_version"], "0.17")\n        self.assertEqual(post["analysis_review_count"], 21)\n        self.assertEqual(post["analysis_evidence_count"], 95)\n        self.assertEqual(post["production_live_input_count"], 1)\n        self.assertEqual(post["production_analysis_revision_count"], 0)\n        self.assertEqual(post["production_exact_timestamp_series_count"], 0)\n\n        live_schema = apply_bb.load(apply_bb.LIVE_SCHEMA_PATH)\n        live_observations = apply_bb.load(apply_bb.LIVE_OBSERVATIONS_PATH)\n        live_evidence = apply_bb.load(apply_bb.LIVE_EVIDENCE_PATH)\n        analysis_schema = apply_bb.load(apply_bb.ANALYSIS_SCHEMA_PATH)\n        reviews = apply_bb.load(apply_bb.ANALYSIS_REVIEWS_PATH)\n        analysis_evidence = apply_bb.load(apply_bb.ANALYSIS_EVIDENCE_PATH)\n        apply_bb.assert_population_descendant_floors(\n            post, live_schema, live_observations, live_evidence, analysis_schema, reviews, analysis_evidence\n        )\n\n        future_schema = copy.deepcopy(live_schema)\n        future_schema["version"] = "0.5"\n        future_observations = copy.deepcopy(live_observations)\n        future_observations["version"] = "0.5"\n        future_observations["observations"].append(copy.deepcopy(future_observations["observations"][0]))\n        future_evidence = copy.deepcopy(live_evidence)\n        future_evidence["version"] = "0.5"\n        future_evidence["evidence"].append(copy.deepcopy(future_evidence["evidence"][0]))\n        apply_bb.assert_population_descendant_floors(\n            post, future_schema, future_observations, future_evidence, analysis_schema, reviews, analysis_evidence\n        )\n\n        below = copy.deepcopy(live_observations)\n        below["observations"] = below["observations"][: post["live_observation_count"] - 1]\n        with self.assertRaises(SystemExit):\n            apply_bb.assert_population_descendant_floors(\n                post, live_schema, below, live_evidence, analysis_schema, reviews, analysis_evidence\n            )\n'''
if old_population_test not in text:
    raise SystemExit('BB population test anchor missing')
text = text.replace(old_population_test, new_population_test, 1)

old_docs_test = '''    def test_status_and_roadmap_advance_without_downstream_pre_authorisation(self) -> None:\n        status = self.target["status"]\n        roadmap = self.target["roadmap"]\n        self.assertIn("Canonical Registry: **v0.39 / 689 occurrences**", status)\n        self.assertIn("Source Registry: **v1.81 / 244 sources**", status)\n        self.assertIn("reviewed Change Ledger: **v0.25 / 60 entries**", status)\n        self.assertIn("No downstream population is pre-authorised", status)\n        self.assertIn("BB — BARMM election source + Canonical coverage repair", roadmap)\n        self.assertIn("no polling clock time, UTC timestamp, result or market response is invented", roadmap)\n'''
new_docs_test = '''    def test_bb_plan_freezes_no_downstream_pre_authorisation_without_current_status_coupling(self) -> None:\n        gates = self.plan["gates"]\n        self.assertFalse(gates["monitor_adapter_added"])\n        self.assertFalse(gates["live_observation_added"])\n        self.assertFalse(gates["analysis_review_or_revision_added"])\n        self.assertFalse(gates["automatic_canonical_commit"])\n        self.assertFalse(gates["google_calendar_write"])\n        self.assertFalse(gates["utc_timestamp_fabricated"])\n        self.assertFalse(gates["future_event_marked_completed"])\n'''
if old_docs_test not in text:
    raise SystemExit('BB docs test anchor missing')
text = text.replace(old_docs_test, new_docs_test, 1)
TEST.write_text(text, encoding='utf-8')

print('BB descendant population/status patch v2 applied')
