from pathlib import Path


def replace_once(path: Path, old: str, new: str) -> None:
    text = path.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected one match, found {count}: {old!r}")
    path.write_text(text.replace(old, new), encoding="utf-8")


readme = Path("README.md")
replace_once(readme, "Post-#76 / AV foundation checkpoint:", "Post-#77 / AW controlled Live Intelligence checkpoint:")
replace_once(readme, "- Live Intelligence: **v0.1 foundation — 0 observations / 0 evidence; population gate closed**", "- Live Intelligence: **v0.2 — 1 reviewed internal observation / 2 primary-official evidence rows; public observation projection closed**")
replace_once(readme, "4. **Live Intelligence** — factual current-development observations; AV v0.1 is foundation-only and intentionally empty.", "4. **Live Intelligence** — factual current-development observations; AW v0.2 contains one controlled internal specimen and still exposes zero public observations.")
replace_once(readme, "AV also emits `docs/data/live_intelligence.json`, but **only as foundation metadata**. It contains no public observations and makes no claim to be a current-news or runtime intelligence feed.", "AW emits `docs/data/live_intelligence.json` as **curated-store metadata only**. The repository contains one reviewed internal observation, but the projection still contains zero public observations and makes no claim to be a current-news or runtime intelligence feed.")
replace_once(
    readme,
    "## Live Intelligence foundation\n\nAV v0.1 makes the Charter's missing Live Intelligence layer executable without populating it prematurely.\n\nThe foundation:\n\n- allows genuinely unscheduled observations to exist without fabricated canonical events;\n- allows optional links to existing canonical occurrences;\n- separates observation time, source-publication time and real-world event time;\n- preserves corrections/revisions rather than silently rewriting history;\n- prohibits causal interpretation and market-move attribution;\n- prohibits Live evidence from altering canonical provenance or resolving missing canonical time;\n- prohibits retrospective migration of Analysis evidence merely to make the new layer appear populated;\n- deliberately rejects production observation/evidence population until a later pressure-audited specimen opens that gate.",
    "## Live Intelligence controlled population\n\nAV v0.1 established the zero-population contract. AW v0.2 opens it only far enough for one reviewed physical-shock specimen: the 26 August 2026 Bhote Koshi / Rasuwa flood in Nepal.\n\nThe controlled state:\n\n- preserves the unscheduled flood without fabricating a Canonical occurrence;\n- preserves the authoritative `Asia/Kathmandu` local time `08:40` and matching `02:55Z`;\n- keeps WORLD SIGNALS observation time separate from real-world event time;\n- adds explicit evidence publication-time precision so civil publication dates cannot be upgraded to invented clock times;\n- contains exactly one internal observation and two primary-official evidence rows;\n- leaves the uncertain upstream physical trigger unresolved rather than promoting a preliminary mechanism into fact;\n- creates no story ID and does not automatically fold the later UN appeal into the shock;\n- prohibits causal interpretation, market-move attribution, Analysis-evidence migration and automatic ingestion;\n- keeps public observation projection closed at zero."
)

architecture = Path("ARCHITECTURE.md")
replace_once(architecture, "Current post-#76 / AV foundation state:", "Current post-#77 / AW controlled Live Intelligence state:")
replace_once(architecture, "- Live Intelligence `v0.1 / 0 observations / 0 evidence`, foundation gate closed;", "- Live Intelligence `v0.2 / 1 internal observation / 2 evidence`, controlled single-specimen gate; public observations `0`;")
replace_once(architecture, "## Live Intelligence foundation\n\nAV introduces the first executable Live Intelligence contract at `data/live_intelligence/`.", "## Live Intelligence controlled population\n\nAV introduced the executable Live Intelligence contract at `data/live_intelligence/`; AW v0.2 admits the first reviewed internal specimen without opening broad ingestion.")
replace_once(architecture, "The AV v0.1 foundation is deliberately **zero-population**. Its validator rejects production observations and evidence until a later pressure-audited specimen explicitly opens the population gate.", "The frozen AV v0.1 checkpoint remains recorded inside the v0.2 schema. AW opens production only under `CONTROLLED_SINGLE_SPECIMEN`: maximum one observation and two evidence rows, automatic ingestion disabled, story clustering disabled and public observation projection closed.")
replace_once(architecture, "Likewise, AV emits `docs/data/live_intelligence.json` only as **foundation metadata**. It contains zero public observations and explicitly states that it is not a runtime feed. A browser Live Intelligence surface should not be introduced until a later population contract is proven.", "Likewise, AW emits `docs/data/live_intelligence.json` only as **curated-store metadata**. It reports one internal observation and two internal evidence rows while exposing zero public observations and explicitly stating that it is not a runtime feed. A browser Live Intelligence feed is not authorised by this tranche.")
replace_once(architecture, "  -> Live Intelligence executable zero-population foundation [AV]\n  -> first pressure-audited Live Intelligence specimen       [NEXT AFTER AV MERGE]", "  -> Live Intelligence executable zero-population foundation [DONE: AV]\n  -> first pressure-audited Live Intelligence specimen       [DONE: AW — Nepal flood]")

roadmap = Path("ROADMAP.md")
replace_once(roadmap, "## Stage 6 — Live Intelligence foundation — AV", "## Stage 6 — Live Intelligence foundation — DONE / AV")
replace_once(roadmap, "**AV v0.1 deliberately prohibits production observation/evidence population.**", "**AV v0.1 deliberately prohibited production observation/evidence population; that frozen foundation checkpoint is preserved inside AW v0.2.**")
replace_once(
    roadmap,
    "## Stage 7 — first Live Intelligence specimen — NEXT AFTER AV MERGE\n\nRun a fresh pressure audit after AV. Choose one real development because it stresses the contract, not because it is convenient or prominent.\n\nCandidate stress classes include:\n\n- unscheduled physical shock;\n- health emergency;\n- geopolitical/policy development;\n- economic-data revision;\n- factual market observation linked to a canonical occurrence.\n\nThe first specimen should test identity, revision, timing, provenance and rights semantics before the population gate is opened more broadly.",
    "## Stage 7 — first Live Intelligence specimen — DONE / AW\n\nAW selected the 26 August 2026 Bhote Koshi / Rasuwa flood in Nepal after comparing physical-shock, health-emergency, geopolitical/policy, economic-revision and market-observation candidates. Selection was based on contract pressure and authoritative provenance rather than headline prominence.\n\nLive Intelligence v0.2 now contains exactly one reviewed internal `PHYSICAL_SHOCK` observation and two primary-official evidence rows. It preserves `Asia/Kathmandu` native time, permits zero Canonical links for a genuinely unscheduled shock, enforces civil-date publication precision for evidence, leaves the uncertain upstream trigger unresolved, creates no story identity and exposes zero public observations.\n\nThe next pressure audit should decide whether repeated as-of state / revision / developing-story semantics now outrank prospective Live Intelligence → Analysis linkage. The 2026 DRC Bundibugyo Ebola outbreak is a strong candidate for that stress test, but is not pre-authorised for population."
)

status = Path("PROJECT_STATUS.md")
replace_once(status, "# CURRENT RECOVERY OVERRIDE — POST-AU / AV FOUNDATION", "# CURRENT RECOVERY OVERRIDE — POST-AV / AW CONTROLLED LIVE INTELLIGENCE")
replace_once(status, "**Exact post-#76 main base:** `a487eaecd6c08e9692a42ce6ffed2dea1e455879`", "**Exact post-#77 main base:** `4768c73532c4ba4038b30314079b85be64fbee01`")
replace_once(status, "**AV branch:** `feature/post-au-pressure-audit-av`", "**AW branch:** `feature/post-av-pressure-audit-aw`")
replace_once(status, "- Live Intelligence: **v0.1 foundation / 0 observations / 0 evidence / production population CLOSED**", "- Live Intelligence: **v0.2 / 1 reviewed internal observation / 2 primary-official evidence rows / public observation projection CLOSED**")
replace_once(
    status,
    "## Current architecture decision\n\nAV pauses further Analysis population. The next architectural step is the executable **Live Intelligence** layer required by the Charter, kept separate from both Source/Change Monitor and Analysis.\n\nAV v0.1 is deliberately foundation-only: its validator rejects production observations/evidence, prohibits causal interpretation and market-move attribution, allows genuinely unscheduled observations without fabricated canonical events, and emits only metadata to the static build. Existing Analysis evidence is not migrated.\n\nAfter AV merges, run a fresh pressure audit before selecting the first Live Intelligence specimen. Japan household spending remains a valid held Analysis specimen, not a queue-completion obligation.",
    "## Current architecture decision\n\nAW has exercised the Live Intelligence contract with its first real specimen without opening a general feed. Live Intelligence v0.2 contains one internally curated physical-shock observation for the 26 August 2026 Nepal Bhote Koshi / Rasuwa flood and exactly two primary-official evidence rows. Public observation projection, automatic ingestion, story clustering, automatic Canonical commit and Google Calendar writes remain closed.\n\nThe specimen has no fabricated Canonical occurrence or link. Native `Asia/Kathmandu` event time is preserved as `2026-08-26T08:40:00` / `2026-08-26T02:55:00Z`; evidence publication dates remain civil-date precision; the uncertain upstream physical trigger is deliberately not asserted as cause.\n\nThe next pressure audit should determine whether Live Intelligence now needs repeated as-of state / revision / developing-story semantics before prospective Live Intelligence → Analysis linkage. The 2026 DRC Bundibugyo Ebola outbreak is a strong candidate but is not pre-authorised. Japan household spending remains a valid held Analysis specimen, not a queue-completion obligation."
)

print("AW current-state documentation patch applied")
