"""Read-only official-source adapters for WORLD SIGNALS.

Adapters may fetch and parse authoritative sources. They do not mutate canonical data.
"""

from .base import AdapterError, FetchSnapshot
from .cbam import (
    CBAM_CERTIFICATE_SALE_AMENDING_CELEX,
    CBAM_PARENT_CELEX,
    CBAM_VERIFICATION_CELEX,
    CBAMAnnualDeadlineRule,
    CBAMMilestoneRule,
    fetch_cbam_annual_declaration_surrender_rule,
    fetch_cbam_certificate_sale_rule,
    fetch_cbam_verification_report_rule,
    parse_cbam_annual_declaration_surrender_rule,
    parse_cbam_certificate_sale_rule,
    parse_cbam_verification_report_rule,
)
from .cellar import (
    CELLAR_CELEX_BASE,
    ELI_IDENTIFIER_BASE,
    EURLEX_ELI_FETCH_BASE,
    CRA_CELEX,
    CRA_ELI_CURRENT,
    ELILegalState,
    cellar_celex_url,
    eli_current_url,
    eli_current_fetch_url,
    cellar_document_text,
    cellar_representation_diagnostics,
    fetch_cellar_celex_document,
    fetch_eli_current_document,
    fetch_cra_article_71,
    parse_cra_article_71,
    parse_eli_current_state,
)
from .cellar_metadata import (
    CellarLegalTopology,
    fetch_cellar_identifier_notice,
    fetch_cellar_rdf_notice,
    normalize_cellar_legal_topology,
    parse_cellar_identifier_notice,
    parse_cellar_legal_relation_diagnostics,
)
from .eia_wpsr import (
    EIA_WPSR_SCHEDULE_URL,
    EIA_WPSR_TIMEZONE,
    EIAWPSRSchedule,
    fetch_eia_wpsr_schedule,
    parse_eia_wpsr_schedule_html,
)
from .japan_mof_jgb import (
    JAPAN_MOF_JGB_CALENDAR_INDEX,
    JAPAN_MOF_TIMEZONE,
    JGBAuctionEntry,
    JGBMonthlyAuctionCalendar,
    fetch_jgb_monthly_auction_calendar,
    jgb_monthly_calendar_url,
    parse_jgb_monthly_auction_calendar_html,
)
from .kenya_law import (
    KENYA_PFM_BASELINE_2025_11_04,
    KENYA_PFM_CURRENT,
    fetch_kenya_budget_policy_rule_baseline,
    fetch_kenya_budget_policy_rule_current,
    parse_kenya_budget_policy_rule,
)
from .ons_release_calendar import (
    ONS_RELEASE_CALENDAR,
    ONS_RELEASE_CALENDAR_RSS_ACCEPT,
    ONSReleaseItem,
    fetch_ons_release_calendar_page,
    fetch_ons_upcoming_releases,
    ons_release_calendar_rss_url,
    parse_ons_release_calendar_rss,
)
from .rba_fsr import RBA_FSR_RSS, fetch_rba_fsr, parse_rba_fsr_rss
from .socrata import (
    SUIN_DATASET_ID,
    fetch_suin_metadata,
    fetch_suin_rows,
    parse_socrata_metadata,
    parse_socrata_rows,
    resource_url,
)

__all__ = [
    "AdapterError",
    "CBAM_CERTIFICATE_SALE_AMENDING_CELEX",
    "CBAM_PARENT_CELEX",
    "CBAM_VERIFICATION_CELEX",
    "CBAMAnnualDeadlineRule",
    "CBAMMilestoneRule",
    "CELLAR_CELEX_BASE",
    "ELI_IDENTIFIER_BASE",
    "EURLEX_ELI_FETCH_BASE",
    "CRA_CELEX",
    "CRA_ELI_CURRENT",
    "ELILegalState",
    "CellarLegalTopology",
    "EIA_WPSR_SCHEDULE_URL",
    "EIA_WPSR_TIMEZONE",
    "EIAWPSRSchedule",
    "FetchSnapshot",
    "JAPAN_MOF_JGB_CALENDAR_INDEX",
    "JAPAN_MOF_TIMEZONE",
    "JGBAuctionEntry",
    "JGBMonthlyAuctionCalendar",
    "KENYA_PFM_BASELINE_2025_11_04",
    "KENYA_PFM_CURRENT",
    "ONS_RELEASE_CALENDAR",
    "ONS_RELEASE_CALENDAR_RSS_ACCEPT",
    "ONSReleaseItem",
    "RBA_FSR_RSS",
    "SUIN_DATASET_ID",
    "cellar_celex_url",
    "eli_current_url",
    "eli_current_fetch_url",
    "cellar_document_text",
    "cellar_representation_diagnostics",
    "fetch_cbam_annual_declaration_surrender_rule",
    "fetch_cbam_certificate_sale_rule",
    "fetch_cbam_verification_report_rule",
    "fetch_cellar_celex_document",
    "fetch_cellar_identifier_notice",
    "fetch_cellar_rdf_notice",
    "fetch_eia_wpsr_schedule",
    "fetch_eli_current_document",
    "fetch_cra_article_71",
    "fetch_jgb_monthly_auction_calendar",
    "fetch_kenya_budget_policy_rule_baseline",
    "fetch_kenya_budget_policy_rule_current",
    "fetch_ons_release_calendar_page",
    "fetch_ons_upcoming_releases",
    "fetch_rba_fsr",
    "fetch_suin_metadata",
    "fetch_suin_rows",
    "jgb_monthly_calendar_url",
    "normalize_cellar_legal_topology",
    "ons_release_calendar_rss_url",
    "parse_cbam_annual_declaration_surrender_rule",
    "parse_cbam_certificate_sale_rule",
    "parse_cbam_verification_report_rule",
    "parse_cra_article_71",
    "parse_cellar_identifier_notice",
    "parse_cellar_legal_relation_diagnostics",
    "parse_eia_wpsr_schedule_html",
    "parse_eli_current_state",
    "parse_jgb_monthly_auction_calendar_html",
    "parse_kenya_budget_policy_rule",
    "parse_ons_release_calendar_rss",
    "parse_rba_fsr_rss",
    "parse_socrata_metadata",
    "parse_socrata_rows",
    "resource_url",
]
